<?php
$records = $this->view_data;
$ctrl = new BillController;
?>

<div>
    <div class="bg-white">
        <table class="table table-hover table-sm">
            <thead class="table-header">
                <tr>
                    <th>Student</th>
                    <th>Due </th>
                    <th>Paid </th>
                    <th>Balance</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php
                $CTOTAL = 0;
                $TOTALPAID = 0;
                $TOTALBALANCE = 0; 
                foreach($records as $data){ 
                $due = billDue($data['pid']);
                $paid = billPaid($data['pid'],'','amountDue');
                $balance = ($due - $paid);
                $CTOTAL = $CTOTAL + $due;
                $TOTALPAID = $TOTALPAID + $paid;
                $TOTALBALANCE = $TOTALBALANCE + $balance;
                ?>
                <tr>
                    <td><a><?=$data['fullname']?></a></td>
                    <td><?=$due?></td>
                    <td><?=$paid?></td>
                    <td><?=$balance?></td>
                    <td><i class="pi pi-ellipsis-h"></i></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
        <hr/>
        <table class="table table-borderless">
            <tfoot>
                <tr>
                    <th class="text-black">CUMULATIVE TOTAL</th>
                    <th><h4>GHc <?=approximate($CTOTAL)?></h4></th>
                    <th></th>
                    <th></th>
                </tr>
                <tr>
                    <th class="text-black">TOTAL PAID</th>
                    <th><h4>GHc <?=approximate($TOTALPAID)?></h4></th>
                    <th></th>
                    <th></th>
                </tr>
                <tr>
                    <th class="text-black">TOTAL BALANCE </th>
                    <th><h4>GHc <?=approximate($TOTALBALANCE)?></h4></th>
                    <th></th>
                    <th></th>
                </tr>
            </tfoot>  
        </table>
        <hr/>
        <div class="text-center small">
            <div>This page is exclusively generated by SMS</div>
            <div>For more infomation, contact the school administrations</div>
            <div> phone: 123456789, email: admin@school.com.</div>
        </div>
    </div>
</div>