<?php
$session = $data['academicSession'];
$year = $data['academicYear'];
$classroom = $data['classroom'];
$status = $data['status'];
?>

<div class="reportBody">
<div class="content">
    <?php include MAKEUPS.'letterHead.php';?>
    <hr/>
    <?php include MAKEUPS.'resultHead.php';?>
    <div>
        <?php 
        $path = $status==1?'list':'result';
        $query = "?assessmentsforastudent.session=$session";
        $query = $query."&assessmentsforastudent.academicYear=$year";
        $query = $query."&assessmentsforastudent.classroom=$classroom";
        echo render_data("assessmentsforastudent/$path/student/$data[studentID]$query")
        ?>
    </div>
    <div>
        <div class="row justify-content-center">
            <div class="col-md-4 col-12 order-3 order-md-1"><?php include MAKEUPS.'gradingTable.php';?></div>
            <div class="col-auto mb-3 order-2"><?php include MAKEUPS.'resultRemarks.php';?></div>
        </div>
    </div>
    <hr/>
    <div class="text-center small">
        <div>This page is exclusively generated by SMS</div>
        <div>For more infomation, contact the school administrations</div>
        <div> phone: 123456789, email: admin@school.com.</div>
    </div>
    <div class="waterMark fit-object">
        <img src="<?php print_link(set_img_src(SCHOOL_LOGO,400,400));?>" alt=""/>
    </div>
    
</div>
</div>

<style>
.reportBody {
  background: white; /* Set your background color here */
  position: relative;
}
.reportBody::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: repeating-linear-gradient(45deg, transparent, transparent 2px, #f0e68c 2px, white 4px);
  background-size: 10px 20px; /* Adjust the size of the wave pattern */
  pointer-events: none;
  opacity: 0.388;
}
.reportBody .content {
  padding: 20px;
  position: relative;
  overflow: hidden;
  z-index: 1; /* Ensure content appears above the noise background */
}
.reportBody .content th,.reportBody .content td{
    color: black;
    border-color: #d3b724 !important;
}
.reportBody .content .text-primary{
    color: #d3b724 !important;
}
.reportBody .content .grading.bg-light, .reportBody .content hr{
    border-color: #d3b724 !important;
    background: unset !important;
}
.reportBody .content .table-header::after{
    background: #f0e68c !important;
} 
.reportBody .content .waterMark{
    position: absolute;
    left: -100px;
    width: 400px;
    height: 400px;
    bottom:0px;
    opacity: 0.038;
    z-index: -1;
}
#page-report-body + div.border-top{
    display: none;
}
</style>